version: "3.8"

services:
  elasticsearch:
    build: ./
    container_name: try-elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./dict:/usr/share/elasticsearch/config/dict

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: try-kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
       - 5601:5601

  data:
    restart: always
    build: ./data/
    container_name: try-data
    working_dir: '/root/data'
    tty: true
    volumes:
      - ./data/:/root/data
    command: tail -f /dev/null

